version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/shenanigansd/scratchpad"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
