[project]
name = "scratchpad"
version = "0.0.0" # explicity non-versioned
description = "A scratchpad for keeping assorted notes and snippets"
authors = [
    { name = "Bradley Reynolds", email = "bradley.reynolds@darbia.dev" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "darbiadev-utilities",
    "toml",
    "pandas",
    "parse",
    "einspect",
]

[project.urls]
repository = "https://github.com/shenanigansd/scratchpad"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "black[jupyter]",
    "ruff",
]
tests = [
    "pytest",
    "hypothesis",
]
docs = [
    "sphinx",
    "sphinxcontrib-autoprogram",
    "sphinx-rtd-theme",
    "toml",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

[tool.black]
target-version = ["py311"]
line-length = 120

[tool.ruff]
target-version = "py311"
line-length = 120
select = ["ALL"]
exclude = ["events","scratch/discarded"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
addopts = "-r a -v"
