name: "Assorted CI - Python"

on:
  push:
    paths:
      - "pyproject.toml"
      - "**/*.py"

jobs:
  assorted:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: "Install dependencies"
        run: |
          python -m pip install --editable .[dev,tests]
          python -m pip install --editable scratch/projects/one_two_three

      - name: "Run tests"
        run:  python -m pytest
