name: "Assorted CI - Rust"

on:
  push:
    paths:
      - ".github/workflows/assorted-rust.yaml"
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@5f704c2b5aa4a48d52e37e40ba540b15620e45b5 # v1.1.2

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@5f704c2b5aa4a48d52e37e40ba540b15620e45b5 # v1.1.2

  test:
    needs: "clippy"
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@5f704c2b5aa4a48d52e37e40ba540b15620e45b5 # v1.1.2
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}
