name: "Assorted CI - Rust"

on:
  push:
    paths:
      - ".github/workflows/assorted-rust.yaml"
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@068870f051676db9e2651013f7c7196ffdaeadaa # v2.0.0

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@068870f051676db9e2651013f7c7196ffdaeadaa # v2.0.0

  test:
    needs: "clippy"
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@068870f051676db9e2651013f7c7196ffdaeadaa # v2.0.0
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}
