name: "Assorted CI - Python"

on:
  push:
    paths:
      - ".github/workflows/assorted-python.yaml"
      - "pyproject.toml"
      - "**/*.py"

jobs:
  assorted:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Setup Python"
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: "Install dependencies"
        run: |
          python -m pip install --editable .[dev,tests]
          python -m pip install --editable scratch/projects/one_two_three

      - name: "Run tests"
        run:  python -m pytest
